import { useState } from "react";
import Swal from "sweetalert2";
import { jsPDF } from "jspdf";
import "jspdf-autotable";
import { FileCheck2, Activity, Download } from "lucide-react";
import { healthDatabase } from "../../utils/healthDatabase";

export default function ReportsPanel() {
  const [fhsisMonth, setFhsisMonth] = useState("January");
  const [fhsisYear, setFhsisYear] = useState("2025");
  const [pidsrWeek, setPidsrWeek] = useState("Morbidity Week 40");

  const generateFHSIS = () => {
    const doc = new jsPDF();
    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    doc.text("REPUBLIC OF THE PHILIPPINES", 105, 20, { align: "center" });
    doc.text("DEPARTMENT OF HEALTH", 105, 27, { align: "center" });
    doc.setFontSize(11);
    doc.setFont("helvetica", "normal");
    doc.text("Municipal Health Office - Murcia, Negros Occidental", 105, 34, {
      align: "center",
    });
    doc.setLineWidth(0.5);
    doc.line(20, 40, 190, 40);

    doc.setFontSize(12);
    doc.setFont("helvetica", "bold");
    doc.text("FHSIS MONTHLY CONSOLIDATION REPORT", 20, 50);
    doc.setFont("helvetica", "normal");
    doc.text(`Period: ${fhsisMonth} ${fhsisYear}`, 20, 57);
    doc.text(`Generated By: System Admin (HEALTH-INTEL)`, 20, 64);
    doc.text(`Date of Export: ${new Date().toLocaleDateString()}`, 20, 71);

    const rawData = healthDatabase[fhsisYear]?.morbidity?.all || [];
    const tableData = rawData
      .slice(0, 8)
      .map((item, index) => [
        index + 1,
        item.disease,
        "Morbidity",
        item.cases.toLocaleString(),
        "Verified",
      ]);

    doc.autoTable({
      startY: 80,
      head: [
        ["No.", "Disease / Indicator", "Category", "Total Cases", "Status"],
      ],
      body: tableData,
      theme: "grid",
      headStyles: { fillColor: [16, 185, 129] },
      styles: { font: "helvetica", fontSize: 10 },
    });

    const finalY = doc.lastAutoTable.finalY || 100;
    doc.setFont("helvetica", "bold");
    doc.text("CERTIFICATION:", 20, finalY + 20);
    doc.setFont("helvetica", "normal");
    doc.text(
      "I hereby certify that the above data is true and correct based on the consolidated",
      20,
      finalY + 27,
    );
    doc.text(
      "reports submitted by the Barangay Health Stations.",
      20,
      finalY + 34,
    );
    doc.line(120, finalY + 60, 180, finalY + 60);
    doc.text("Municipal Health Officer", 150, finalY + 66, { align: "center" });

    doc.save(`HEALTH-INTEL_FHSIS_${new Date().getTime()}.pdf`);
    Swal.fire({
      icon: "success",
      title: "PDF Generated Successfully",
      text: "The FHSIS report has been locked and downloaded.",
      confirmButtonColor: "#10b981",
    });
  };

  const generatePIDSR = () => {
    const doc = new jsPDF();
    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    doc.text("REPUBLIC OF THE PHILIPPINES", 105, 20, { align: "center" });
    doc.text("DEPARTMENT OF HEALTH", 105, 27, { align: "center" });
    doc.setFontSize(11);
    doc.setFont("helvetica", "normal");
    doc.text("Municipal Health Office - Murcia, Negros Occidental", 105, 34, {
      align: "center",
    });
    doc.setLineWidth(0.5);
    doc.line(20, 40, 190, 40);

    doc.setFontSize(12);
    doc.setFont("helvetica", "bold");
    doc.text("PIDSR EPIDEMIOLOGICAL SURVEILLANCE REPORT", 20, 50);
    doc.setFont("helvetica", "normal");
    doc.text(`Period: ${pidsrWeek}, CY 2025`, 20, 57);
    doc.text(`Generated By: System Admin (HEALTH-INTEL)`, 20, 64);
    doc.text(`Date of Export: ${new Date().toLocaleDateString()}`, 20, 71);

    const tableData = [
      [1, "Dengue Fever", "High Risk", "15", "Alert Threshold"],
      [2, "Acute Gastroenteritis", "Standard", "34", "Monitored"],
      [3, "Typhoid Fever", "High Risk", "2", "Isolated"],
      [4, "Cholera", "High Risk", "0", "Clear"],
    ];

    doc.autoTable({
      startY: 80,
      head: [
        ["No.", "Disease / Indicator", "Category", "Total Cases", "Status"],
      ],
      body: tableData,
      theme: "grid",
      headStyles: { fillColor: [239, 68, 68] },
      styles: { font: "helvetica", fontSize: 10 },
    });

    const finalY = doc.lastAutoTable.finalY || 100;
    doc.setFont("helvetica", "bold");
    doc.text("CERTIFICATION:", 20, finalY + 20);
    doc.setFont("helvetica", "normal");
    doc.text(
      "I hereby certify that the above data is true and correct based on the consolidated",
      20,
      finalY + 27,
    );
    doc.text(
      "reports submitted by the Barangay Health Stations.",
      20,
      finalY + 34,
    );
    doc.line(120, finalY + 60, 180, finalY + 60);
    doc.text("Municipal Health Officer", 150, finalY + 66, { align: "center" });

    doc.save(`HEALTH-INTEL_PIDSR_${new Date().getTime()}.pdf`);
    Swal.fire({
      icon: "success",
      title: "PDF Generated Successfully",
      text: "The PIDSR report has been locked and downloaded.",
      confirmButtonColor: "#ef4444",
    });
  };

  return (
    <div>
      <h2 className="text-2xl font-bold text-gray-900">
        Official DOH Report Generation
      </h2>
      <p className="text-gray-600 mb-6">
        Generate immutable, print-ready PDF documents formatted for regional
        Department of Health submission.
      </p>

      <div className="grid grid-cols-2 gap-6">
        {/* FHSIS */}
        <div className="bg-white rounded-xl shadow-sm border-t-4 border-green-500 p-6">
          <h3 className="font-bold text-gray-900 flex items-center gap-2">
            <FileCheck2 className="w-5 h-5 text-green-500" />
            FHSIS Consolidation
          </h3>
          <p className="text-sm text-gray-600 mt-2 mb-4">
            Field Health Services Information System. Monthly summary of
            morbidity and mortality across all barangays.
          </p>
          <div className="flex gap-2 mb-4">
            <select
              value={fhsisMonth}
              onChange={(e) => setFhsisMonth(e.target.value)}
              className="flex-1 px-3 py-2 border border-gray-300 rounded-md"
            >
              <option value="January">January</option>
              <option value="February">February</option>
              <option value="March">March</option>
            </select>
            <select
              value={fhsisYear}
              onChange={(e) => setFhsisYear(e.target.value)}
              className="flex-1 px-3 py-2 border border-gray-300 rounded-md"
            >
              <option value="2025">2025</option>
              <option value="2024">2024</option>
            </select>
          </div>
          <button
            onClick={generateFHSIS}
            className="w-full flex items-center justify-center gap-2 bg-green-500 hover:bg-green-600 text-white font-bold py-2 px-4 rounded-md transition"
          >
            <Download className="w-5 h-5" />
            Download Certified PDF
          </button>
        </div>

        {/* PIDSR */}
        <div className="bg-white rounded-xl shadow-sm border-t-4 border-red-500 p-6">
          <h3 className="font-bold text-gray-900 flex items-center gap-2">
            <Activity className="w-5 h-5 text-red-500" />
            PIDSR Surveillance
          </h3>
          <p className="text-sm text-gray-600 mt-2 mb-4">
            Philippine Integrated Disease Surveillance and Response. Weekly
            tracking of outbreak-prone cases.
          </p>
          <div className="mb-4">
            <select
              value={pidsrWeek}
              onChange={(e) => setPidsrWeek(e.target.value)}
              className="w-full px-3 py-2 border border-gray-300 rounded-md"
            >
              <option value="Morbidity Week 40">Morbidity Week 40</option>
              <option value="Morbidity Week 41">Morbidity Week 41</option>
              <option value="Morbidity Week 42">Morbidity Week 42</option>
            </select>
          </div>
          <button
            onClick={generatePIDSR}
            className="w-full flex items-center justify-center gap-2 bg-red-500 hover:bg-red-600 text-white font-bold py-2 px-4 rounded-md transition"
          >
            <Download className="w-5 h-5" />
            Download Certified PDF
          </button>
        </div>
      </div>
    </div>
  );
}
