// src/utils/healthDatabase.js

export const healthDatabase = {
  2025: {
    morbidity: {
      all: [
        { disease: "Wounds & Animal Bites", cases: 3674 },
        { disease: "Other Symptoms", cases: 712 },
        { disease: "Upper Resp. Infection (URTI)", cases: 695 },
        { disease: "Influenza", cases: 673 },
        { disease: "Fever (Unknown Origin)", cases: 490 },
        { disease: "Acute Lower Resp. Infection", cases: 344 },
        { disease: "Essential Hypertension", cases: 320 },
        { disease: "Abdominal & Pelvic pain", cases: 212 },
        { disease: "Other Diseases of Skin", cases: 121 },
        { disease: "Urinary Tract Infection", cases: 94 },
      ],
      under5: [
        { disease: "Wounds (inc. Animal bites)", cases: 368 },
        { disease: "Influenza", cases: 224 },
        { disease: "Acute URTI", cases: 210 },
        { disease: "Fever (Unknown Origin)", cases: 133 },
        { disease: "Other Symptoms", cases: 60 },
        { disease: "Unspecified lower resp.", cases: 46 },
        { disease: "Nose/nasal diseases", cases: 40 },
        { disease: "Acute Gastroenteritis", cases: 34 },
        { disease: "Skin Diseases", cases: 33 },
        { disease: "Asthma", cases: 13 },
      ],
      infant: [
        { disease: "Acute URTI", cases: 41 },
        { disease: "Influenza", cases: 41 },
        { disease: "Fever (Unknown Origin)", cases: 13 },
        { disease: "Wounds, All Types", cases: 8 },
        { disease: "Acute Gastroenteritis", cases: 7 },
        { disease: "Skin Diseases", cases: 6 },
        { disease: "Unspecified Acute Lower Resp.", cases: 6 },
        { disease: "Nose/nasal diseases", cases: 4 },
        { disease: "Relapsing fever", cases: 3 },
        { disease: "Other Symptoms", cases: 3 },
      ],
    },
    mortality: {
      all: [
        { disease: "Undetermined Natural Cause", cases: 74 },
        { disease: "Hypertension", cases: 66 },
        { disease: "Tuberculosis", cases: 28 },
        { disease: "Diabetes Mellitus", cases: 22 },
        { disease: "Kidney Disease", cases: 20 },
        { disease: "Cardio Pulmonary Arrest", cases: 20 },
        { disease: "Cancer", cases: 19 },
        { disease: "Pneumonia", cases: 18 },
        { disease: "Accident", cases: 14 },
        { disease: "Wounds, All Types", cases: 10 },
      ],
      under5: [
        { disease: "Fetal Death", cases: 6 },
        { disease: "Pneumonia", cases: 2 },
        { disease: "Prematurity", cases: 1 },
        { disease: "Congenital Anomaly", cases: 1 },
      ],
      infant: [
        { disease: "Fetal Death", cases: 6 },
        { disease: "Prematurity", cases: 1 },
        { disease: "Pneumonia", cases: 1 },
      ],
    },
  },
  2024: {
    morbidity: {
      all: [
        { disease: "Acute Resp. Infection", cases: 2037 },
        { disease: "Animal Bites", cases: 2004 },
        { disease: "Fever (Unknown Origin)", cases: 1396 },
        { disease: "Wound - All Types", cases: 515 },
        { disease: "Body Malaise/Pain", cases: 263 },
        { disease: "Hypertension", cases: 110 },
        { disease: "Acute Gastroenteritis", cases: 99 },
        { disease: "Systemic Viral Infection", cases: 95 },
        { disease: "Skin Diseases", cases: 88 },
        { disease: "Hypersensitivity Reaction", cases: 88 },
      ],
      under5: [
        { disease: "Fever (Unknown Origin)", cases: 488 },
        { disease: "Acute Resp. Infection", cases: 396 },
        { disease: "Cough", cases: 248 },
        { disease: "Animal Bites", cases: 239 },
        { disease: "Wounds, All Types", cases: 64 },
        { disease: "Hypersensitivity Reaction", cases: 37 },
        { disease: "Influenza", cases: 35 },
        { disease: "Skin Diseases", cases: 23 },
        { disease: "Systemic Viral Infection", cases: 21 },
        { disease: "Asthma", cases: 15 },
      ],
      infant: [
        { disease: "Acute Resp. Infection", cases: 133 },
        { disease: "Fever (Unknown Origin)", cases: 95 },
        { disease: "Cough", cases: 60 },
        { disease: "Influenza", cases: 12 },
        { disease: "Acute Gastroenteritis", cases: 9 },
        { disease: "Skin Diseases", cases: 7 },
        { disease: "Hypersensitivity Reaction", cases: 7 },
        { disease: "Systemic Viral Infection", cases: 7 },
        { disease: "Wounds, All Types", cases: 4 },
        { disease: "Whooping Cough", cases: 3 },
      ],
    },
    mortality: {
      all: [
        { disease: "Undetermined Natural Cause", cases: 91 },
        { disease: "Hypertension", cases: 46 },
        { disease: "Cancer", cases: 30 },
        { disease: "Kidney Disease", cases: 27 },
        { disease: "Diabetes Mellitus", cases: 26 },
        { disease: "Pneumonia", cases: 12 },
        { disease: "Tuberculosis", cases: 12 },
        { disease: "Accident", cases: 12 },
        { disease: "COPD", cases: 10 },
        { disease: "Cardiovascular Disease", cases: 8 },
      ],
      under5: [
        { disease: "Fetal Death", cases: 7 },
        { disease: "Pneumonia", cases: 3 },
        { disease: "Prematurity", cases: 1 },
        { disease: "Congenital Anomaly", cases: 1 },
      ],
      infant: [
        { disease: "Fetal Death", cases: 7 },
        { disease: "Prematurity", cases: 1 },
        { disease: "Pneumonia", cases: 1 },
      ],
    },
  },
  2023: {
    morbidity: {
      all: [
        { disease: "Cough", cases: 793 },
        { disease: "Animal Bites", cases: 599 },
        { disease: "URTI", cases: 353 },
        { disease: "Wounds, All Type", cases: 272 },
        { disease: "ARI", cases: 271 },
        { disease: "Fever (Unknown Origin)", cases: 216 },
        { disease: "Hypertension", cases: 213 },
        { disease: "Influenza", cases: 155 },
        { disease: "Acute Gastroenteritis", cases: 155 },
        { disease: "Vertigo", cases: 120 },
      ],
      under5: [
        { disease: "Cough", cases: 171 },
        { disease: "Fever (Unknown Origin)", cases: 83 },
        { disease: "ARI", cases: 82 },
        { disease: "URTI", cases: 66 },
        { disease: "Animal Bites", cases: 46 },
        { disease: "Acute Gastroenteritis", cases: 29 },
        { disease: "Systemic Viral Infection", cases: 17 },
        { disease: "Hand, Foot & Mouth", cases: 12 },
        { disease: "Wounds, All Type", cases: 8 },
        { disease: "Otitis Media", cases: 4 },
      ],
      infant: [
        { disease: "Cough", cases: 64 },
        { disease: "ARI", cases: 29 },
        { disease: "Fever (Unknown Origin)", cases: 20 },
        { disease: "URTI", cases: 12 },
        { disease: "Acute Gastroenteritis", cases: 4 },
        { disease: "Systemic Viral Infection", cases: 3 },
        { disease: "Skin Diseases", cases: 3 },
        { disease: "Carbuncle", cases: 2 },
        { disease: "Hypersensitivity", cases: 2 },
        { disease: "Wound, All Type", cases: 1 },
      ],
    },
    mortality: {
      all: [
        { disease: "Undetermined Natural Cause", cases: 92 },
        { disease: "Hypertension", cases: 60 },
        { disease: "Cardiopulmonary Arrest", cases: 29 },
        { disease: "Kidney Disease", cases: 20 },
        { disease: "Cancer", cases: 19 },
        { disease: "Pneumonia", cases: 15 },
        { disease: "Tuberculosis", cases: 12 },
        { disease: "Accident", cases: 8 },
        { disease: "COPD", cases: 7 },
        { disease: "Asphyxia", cases: 5 },
      ],
      under5: [
        { disease: "Fetal Death", cases: 3 },
        { disease: "Acute Gastroenteritis", cases: 3 },
        { disease: "Pneumonia", cases: 1 },
        { disease: "Prematurity", cases: 1 },
        { disease: "Sepsis", cases: 1 },
      ],
      infant: [
        { disease: "Fetal Death", cases: 3 },
        { disease: "Pneumonia", cases: 1 },
        { disease: "Acute Gastroenteritis", cases: 1 },
        { disease: "Prematurity", cases: 1 },
      ],
    },
  },
};
